[project]
name = "wss-tool"
version = "1.0.3"
description = "Tool untuk rename (OCR) dan georeferencing peta WSS"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.0.0",
    "numpy>=1.20.0",
    "rapidocr-onnxruntime>=1.2.0",
    "pandas>=2.0",
    "PyQt5>=5.15",
]

[project.scripts]
wss-tool = "wss_tool.cli:main"
wss-tool-gui = "wss_tool.gui:main"
